#!/bin/sh


bat_stat() {
    for battery in /sys/class/power_supply/BAT?*; do
        # If non-first battery, print a space separator.
        [ -n "${capacity+x}" ] && printf " "
        # Sets up the status and capacity
        case "$(cat "$battery/status" 2>&1)" in
            "Full") status="" ;;
            "Discharging") status="" ;;
            "Charging") status=" " ;;
            "Not charging") status=" " ;;
            "Unknown") status="" ;;
            *) exit 1 ;;
        esac
        capacity="$(cat "$battery/capacity" 2>&1)"
        # Will make a warn variable if discharging and lo
        [ "$status" = "" ] && [ "$capacity" -le 25 ] && warn=""

        # Prints the info
        printf "%s %s%d%%" "$status" "$warn" "$capacity"; unset warn
    done && printf "\\n"
}

vol() {
    vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep 'Volume' | cut -d '%' -f 1 | cut -d '/' -f 2 | tr -d ' ')

    if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = 'Mute: yes' ] ; then
        vol="󰝟"
    elif [ "$vol" -le 20 ]
    then
        vol=" $vol%"
    elif [ "$vol%" -le 40  ]
    then
        vol=" $vol%"
    elif [ "$vol" -le 60 ]
    then
        vol="󰕾 $vol%"
    else
        vol=" $vol%"
    fi

    echo "$vol"
}

net_traf() {
    update() {
        sum=0
        for arg; do
            read -r i < "$arg"
            sum=$(( sum + i ))
        done
        cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
        [ -f "$cache" ] && read -r old < "$cache" || old=0
        printf %d\\n "$sum" > "$cache"
        printf %d\\n $(( sum - old ))
    }

    rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
    tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

    printf "   %4sB   %4sB \\n" $(numfmt --to=iec $rx $tx)
}

salat_time() {
    dur='/tmp/salah-time-dur-status'
    cashed='/tmp/salah-time-dur-status-cashed'

    if [ -f "$dur" ]
    then
        tm=$(cat "$dur")
        if [ "$tm" -ge 1200 ]
        then
            echo "1" > "$dur"
            time=$(~/.config/sway/scripts/salaht)
            echo "$time" > "$cashed"
            echo "$time"
        else
            echo "$(($tm + 1))" > "$dur"
            cat "$cashed"
        fi

    else
        echo "1" > "$dur"
        time=$(~/.config/sway/scripts/salaht)
        echo "$time" > "$cashed"
        echo "$time"
        
    fi


}

net () {
    if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
        wifiicon="  Wifi"
    elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
        grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="⚠ pr" || wifiicon="⚠ down"
    fi

    echo "$wifiicon"
}


back=$(brightnessctl  | grep 'Current' | cut -d '(' -f 2 | cut -d ')' -f 1)

echo "$(net_traf) | $(net) | $(bat_stat)  ${back} | $(vol) | $(salat_time) | $(date '+ %I:%M:%S %p 󰸘 %a %d-%m-%y' )"
