#!/bin/bash


# $(pactl get-sink-volume @DEFAULT_SINK@ | grep 'Volume' | cut -d '%' -f 1 | cut -d '/' -f 2 | tr -d ' ')
# pactl set-sink-volume @DEFAULT_SINK@ -5%


function send_notification() {
	volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep 'Volume' | cut -d '%' -f 1 | cut -d '/' -f 2 | tr -d ' ')
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	pactl set-sink-volume @DEFAULT_SINK@ +5%
	send_notification "$1"
	;;
down)
	pactl set-sink-volume @DEFAULT_SINK@ -5%
	send_notification "$1"
	;;
mute)
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = 'Mute: yes' ] ; then
		dunstify -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
