#! /bin/sh

path="$HOME/.cache/stime"

curl -s 'https://hamariweb.com/islam/tangail_prayer-timing13785.aspx' |
    grep 'data-label="Fajr"\|data-label="Sunrise"\|data-label="Dhuhr"\|data-label="Asr"\|data-label="Maghrib"\|data-label="Isha"' |
    sed  's/<td\ data-label="// ; s/">/\ / ; s/<\/td>// ; s/" class="border-0//' > ${path}/new

## If there is no net then show the archived vertion "cached version"
tim=$( head -1 < "$path/new" )
if [ -z "$tim" ]
then

    time=${path}/old
	[ "$(date +"%H" | sed "s/00/1/")" -ge 1 ] && [ "$(date +"%H")" -le 5 ] && sed -n 1p "$time" && exit 0
	[ "$(date +"%H")" -ge 6 ] && [ "$(date +"%H")" -le 7 ] && sed -n 2p "$time" && exit 0
	[ "$(date +"%H")" -ge 8 ] && [ "$(date +"%H")" -le 13 ] && sed -n 3p "$time" && exit 0
	[ "$(date +"%H")" -ge 14 ] && [ "$(date +"%H")" -le 17 ] && sed -n 4p "$time" && exit 0
	[ "$(date +"%H")" -ge 18 ] && [ "$(date +"%H")" -le 18 ] && sed -n 5p "$time" && exit 0
	[ "$(date +"%H")" -ge 19 ] && [ "$(date +"%H")" -le 24 ] && sed -n 6p "$time" && exit 0

	exit 0
fi

cat ${path}/new > ${path}/old
time=${path}/new
[ "$(date +"%H" | sed "s/00/1/")" -ge 1 ] && [ "$(date +"%H")" -le 5 ] && sed -n 1p "$time" && exit 0
[ "$(date +"%H")" -ge 6 ] && [ "$(date +"%H")" -le 7 ] && sed -n 2p "$time" && exit 0
[ "$(date +"%H")" -ge 8 ] && [ "$(date +"%H")" -le 13 ] && sed -n 3p "$time" && exit 0
[ "$(date +"%H")" -ge 14 ] && [ "$(date +"%H")" -le 17 ] && sed -n 4p "$time" && exit 0
[ "$(date +"%H")" -ge 18 ] && [ "$(date +"%H")" -le 18 ] && sed -n 5p "$time" && exit 0
[ "$(date +"%H")" -ge 19 ] && [ "$(date +"%H")" -le 24 ] && sed -n 6p "$time" && exit 0


