#!/bin/sh

# cache path
path="$HOME/.cache/stime"

# get time in second fomat
toSecond() {
    time="$(date '+%H:%M')" 
    hr=$(echo "$time" | cut -d ':' -f 1)
    min=$(echo "$time" | cut -d ':' -f 2)
    mhr=$((hr*60))
    min=$((min+mhr))
    echo "$((min*60))"
}


# get time and fotmat it
curl -s 'https://hamariweb.com/islam/tangail_prayer-timing13785.aspx' |
    grep 'data-label="Fajr"\|data-label="Sunrise"\|data-label="Dhuhr"\|data-label="Asr"\|data-label="Maghrib"\|data-label="Isha"' |
    sed  's/<td\ data-label="// ; s/">/\ / ; s/<\/td>// ; s/" class="border-0//' > ${path}/new

## If there is no net then show the archived vertion "cached version"
tim=$( head -1 < "$path/new" )
if [ -z "$tim" ]
then
    time=${path}/old

    [ $(toSecond) -ge 1 ] && [ $(toSecond) -le 19200 ] && sed -n 1p "$time" && exit
    [ $(toSecond) -ge 19260 ] && [ $(toSecond) -le 25200 ] && sed -n 2p "$time" && exit
    [ $(toSecond) -ge 25201 ] && [ $(toSecond) -le 49200 ] && sed -n 3p "$time" && exit
    [ $(toSecond) -ge 49201 ] && [ $(toSecond) -le 60000 ] && sed -n 4p "$time" && exit
    [ $(toSecond) -ge 60001 ] && [ $(toSecond) -le 64800 ] && sed -n 5p "$time" && exit
    [ $(toSecond) -ge 64801 ] && [ $(toSecond) -le 86400 ] && sed -n 6p "$time" && exit
    exit
fi


# if net is avialable store it and print it
cat ${path}/new > ${path}/old
time=${path}/new
[ $(toSecond) -ge 1 ] && [ $(toSecond) -le 19200 ] && sed -n 1p "$time" && exit
[ $(toSecond) -ge 19260 ] && [ $(toSecond) -le 25200 ] && sed -n 2p "$time" && exit
[ $(toSecond) -ge 25201 ] && [ $(toSecond) -le 49200 ] && sed -n 3p "$time" && exit
[ $(toSecond) -ge 49201 ] && [ $(toSecond) -le 60000 ] && sed -n 4p "$time" && exit
[ $(toSecond) -ge 60001 ] && [ $(toSecond) -le 64800 ] && sed -n 5p "$time" && exit
[ $(toSecond) -ge 64801 ] && [ $(toSecond) -le 86400 ] && sed -n 6p "$time" && exit
exit
