#!/bin/sh

send_notification() {
	light=$(brightnessctl | grep 'Current brightness:' | cut -d '(' -f 2 | cut -d '%' -f 1)
	dunstify -a "changelight" -u low -r "9993" -h int:value:"$light" -i "light-$1" "Brightness: ${light}%" -t 2000
}

case $1 in
	s)
		brightnessctl set "$2"%
		send_notification "$1"
		;;
	i)
		brightnessctl set 5%+
		send_notification "$1"
		;;
	d)
		brightnessctl set 5%-
		send_notification "$1"
		;;
esac

[ $(brightnessctl | grep 'Current brightness:' | cut -d '(' -f 2 | cut -d '%' -f 1) -le 0 ] && brightnessctl set 1%
